# Generated by Django 6.0.7 on 2026-07-16 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(default='Actif', max_length=50)),
                ('filiere', models.CharField(blank=True, max_length=200)),
                ('niveau', models.CharField(blank=True, max_length=200)),
                ('frais_scolarite', models.FloatField(default=500000)),
            ],
            options={
                'db_table': 'etudiants',
                'ordering': ['-date_ajout'],
                'managed': False,
            },
        ),
    ]
