# Generated by Django 6.0.7 on 2026-07-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='payment',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='students.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_paiement',
            field=models.CharField(default='Espèces', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='frais_scolarite',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tranche', models.IntegerField(help_text='Numéro de la tranche (1, 2, 3...)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='students.student')),
            ],
            options={
                'ordering': ['student', 'numero_tranche'],
                'unique_together': {('student', 'numero_tranche')},
            },
        ),
    ]
