# Generated by Django 6.0.7 on 2026-07-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_log_options_payment_numero_recu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_finances', 'Peut voir les données financières'), ('can_manage_users', 'Peut gérer les utilisateurs'), ('can_delete_student', 'Peut supprimer des étudiants'), ('can_export_data', 'Peut exporter les données'), ('can_view_logs', "Peut voir le journal d'audit")]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text="Verrouillage jusqu'à cette date", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.IntegerField(default=0, help_text='Tentatives de connexion échouées consécutives'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Forcer le changement de mot de passe à la prochaine connexion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
