# Generated by Django 6.0.7 on 2026-07-22 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_cours_absence_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='note',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=4)),
                ('matiere', models.CharField(blank=True, default='Générale', max_length=100)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('semestre', models.CharField(blank=True, default='', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
