# Generated by Django 6.0.7 on 2026-07-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_note_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-matricule']},
        ),
    ]
