# Generated by Django 6.0.7 on 2026-07-23 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_update_student_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('info', 'Information'), ('academique', 'Académique'), ('evenement', 'Événement'), ('urgence', 'Urgence'), ('administratif', 'Administratif')], default='info', max_length=20)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_publiee', models.BooleanField(default=True)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='annonces/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
