# Generated by Django 6.0.7 on 2026-08-30 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='annonces/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
