# Generated by Django 6.0.7 on 2026-08-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_annonce_fichier_joint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_finances', 'Peut voir les données financières'), ('can_manage_users', 'Peut gérer les utilisateurs'), ('can_delete_student', 'Peut supprimer des étudiants'), ('can_export_data', 'Peut exporter les données'), ('can_view_logs', "Peut voir le journal d'audit"), ('can_add_student', 'Peut ajouter un étudiant'), ('can_generate_documents', "Peut générer bulletins et cartes d'étudiant"), ('can_manage_schedule', "Peut créer/modifier l'emploi du temps")]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', "En attente d'approbation")], default='active', max_length=10),
        ),
    ]
