# Generated by Django 6.0.7 on 2026-09-04 17:53

import django.core.validators
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_customuser_options_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='annonces/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif']), students.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[students.models.validate_file_size]),
        ),
    ]
