services:
  - type: web
    name: student-manager-pro
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py ensure_superuser && daphne studentmanager.asgi:application --bind 0.0.0.0 --port $PORT"
    envVars:
      # ----- A definir manuellement dans le dashboard Render (Environment) -----
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
      - key: DATABASE_URL
        sync: false   # chaine de connexion Postgres Supabase
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      # ----- Stockage de fichiers (Supabase Storage, compatible S3) -----
      - key: SUPABASE_STORAGE_BUCKET
        sync: false
      - key: SUPABASE_S3_ENDPOINT_URL
        sync: false
      - key: SUPABASE_S3_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_S3_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_REGION
        value: "us-east-1"
