"""
Django settings for studentmanager project.
Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url
import logging
from logging.handlers import RotatingFileHandler

# Charger le fichier .env
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me')
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

if not DEBUG and SECRET_KEY == 'django-insecure-change-me':
    raise RuntimeError(
        "DJANGO_SECRET_KEY doit être défini via une variable d'environnement en production "
        "(DEBUG=False). Générez-en une avec `python -c \"from django.core.management.utils "
        "import get_random_secret_key; print(get_random_secret_key())\"`."
    )

# Ajouter automatiquement les domaines Railway (health check) et Render
ALLOWED_HOSTS += ['healthcheck.railway.app', '.railway.app', '.onrender.com']

# Ajouter le domaine public Railway si disponible
railway_public_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if railway_public_domain:
    ALLOWED_HOSTS.append(railway_public_domain)

# Render fournit automatiquement le nom d'hôte externe du service
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname:
    ALLOWED_HOSTS.append(render_external_hostname)

INSTALLED_APPS = [
    # 'daphne' doit être le tout premier app installée : cela fait passer
    # `manage.py runserver` en mode ASGI automatiquement (nécessaire pour les
    # WebSockets de la messagerie en temps réel).
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'students',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studentmanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'students.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'studentmanager.wsgi.application'
ASGI_APPLICATION = 'studentmanager.asgi.application'

# ===== CHANNELS (WebSockets — messagerie en temps réel) =====
# En production, définir REDIS_URL (add-on Redis Railway) permet de faire
# fonctionner les WebSockets de façon fiable avec plusieurs workers/instances.
# Sans REDIS_URL, on utilise la couche en mémoire : elle fonctionne correctement
# tant qu'un seul processus ASGI tourne (cas par défaut sur Railway : 1 replica).
_redis_url = os.getenv('REDIS_URL')
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Configuration de la base de données via DATABASE_URL
# conn_max_age réutilise la connexion entre requêtes au lieu d'en rouvrir une
# (handshake TCP/TLS + auth) à chaque requête — critique pour une base distante
# comme Supabase, sinon chaque page paie ce coût même pour une seule requête.
default_db_url = f"sqlite:///{BASE_DIR / 'etudiants.db'}"
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', default_db_url),
        conn_max_age=60,
        conn_health_checks=True,
    )
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Douala'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
AUTH_USER_MODEL = 'students.CustomUser'
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000').split(',')

# Ajouter le domaine public Railway si disponible
if railway_public_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{railway_public_domain}')

# Ajouter le domaine public Render si disponible
if render_external_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_external_hostname}')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ===== STOCKAGE DES FICHIERS (Supabase Storage, compatible S3) =====
# En production (Render), le disque est éphémère : les photos d'étudiants et
# pièces jointes d'annonces uploadées disparaîtraient à chaque redéploiement.
# Si les identifiants Supabase Storage sont fournis via l'environnement, ces
# fichiers sont stockés sur Supabase au lieu du disque local. Sans ces
# variables (ex. en développement local), on reste sur le stockage disque
# classique — aucun changement de comportement en local.
AWS_STORAGE_BUCKET_NAME = os.getenv('SUPABASE_STORAGE_BUCKET', '')
AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_S3_ENDPOINT_URL', '')
AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_S3_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_S3_SECRET_ACCESS_KEY', '')
AWS_S3_REGION_NAME = os.getenv('SUPABASE_S3_REGION', 'us-east-1')
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None       # Supabase gère les permissions via les policies du bucket
AWS_QUERYSTRING_AUTH = False  # URLs publiques simples plutôt que des URLs signées temporaires
AWS_S3_ADDRESSING_STYLE = 'path'  # requis par l'API S3 de Supabase

USE_SUPABASE_STORAGE = bool(
    AWS_STORAGE_BUCKET_NAME and AWS_S3_ENDPOINT_URL and AWS_ACCESS_KEY_ID
)

if USE_SUPABASE_STORAGE:
    # L'URL de l'API S3 (AWS_S3_ENDPOINT_URL, /storage/v1/s3) sert à uploader,
    # mais les fichiers d'un bucket public se lisent via un chemin différent :
    # /storage/v1/object/public/<bucket>/<chemin>. Sans ce réglage, les URLs
    # générées (student.photo.url, etc.) pointent vers l'API S3 et renvoient
    # une erreur 403 pour un accès anonyme depuis le navigateur.
    from urllib.parse import urlparse
    _supabase_host = urlparse(AWS_S3_ENDPOINT_URL).netloc
    AWS_S3_CUSTOM_DOMAIN = f'{_supabase_host}/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}'

STORAGES = {
    'default': {
        'BACKEND': (
            'storages.backends.s3boto3.S3Boto3Storage' if USE_SUPABASE_STORAGE
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        # Le stockage "manifest" (hash dans le nom de fichier, cache navigateur
        # long) exige d'avoir lance `collectstatic` a chaque changement de
        # fichier statique, sinon {% static %} leve une erreur 500 des qu'un
        # fichier n'est pas encore dans le manifeste (staticfiles.json). Genant
        # en dev local ou l'on modifie sans cesse le CSS/JS. On ne l'utilise
        # donc qu'en production (DEBUG=False), ou collectstatic tourne au
        # deploiement (voir Procfile/render.yaml).
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== LOGGING CONFIGURATION (RotatingFileHandler) =====
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()
LOG_MAX_BYTES = int(os.getenv('LOG_MAX_BYTES', 10 * 1024 * 1024))  # 10 MB
LOG_BACKUP_COUNT = int(os.getenv('LOG_BACKUP_COUNT', 5))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_rotating': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'student_manager.log',
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'file_errors': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'errors.log',
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'verbose',
            'level': 'ERROR',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file_rotating'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_rotating'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        'students': {
            'handlers': ['console', 'file_rotating', 'file_errors'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
    },
}

# ===== REST FRAMEWORK CONFIGURATION =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Config GitHub (depuis .env)
GITHUB_USER = os.getenv('GITHUB_USER', '')
GITHUB_REPO = os.getenv('GITHUB_REPO', '')
